# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(951, 642)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 120, 551, 411))
        self.label_2.setStyleSheet("border-image: url(:/images/images/loginBack.jpg);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 120, 551, 411))
        self.label_3.setStyleSheet("background-color: rgba(0, 0, 0, 100);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(780, 130, 79, 44))
        self.frame.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(59, 120, 261, 411))
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_in = QtWidgets.QWidget()
        self.page_in.setObjectName("page_in")
        self.label_4 = QtWidgets.QLabel(self.page_in)
        self.label_4.setGeometry(QtCore.QRect(70, 40, 131, 71))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_u = QtWidgets.QLineEdit(self.page_in)
        self.lineEdit_u.setGeometry(QtCore.QRect(20, 130, 221, 51))
        self.lineEdit_u.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(0,0,0,100);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.lineEdit_u.setObjectName("lineEdit_u")
        self.pushButton_in = QtWidgets.QPushButton(self.page_in)
        self.pushButton_in.setGeometry(QtCore.QRect(10, 300, 111, 51))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_in.setFont(font)
        self.pushButton_in.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(102, 133, 156, 255), stop:1 rgba(117, 255, 201, 255));\n"
"    color: rgb(255, 255, 255);\n"
"    border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_in.setObjectName("pushButton_in")
        self.pushButton_up = QtWidgets.QPushButton(self.page_in)
        self.pushButton_up.setGeometry(QtCore.QRect(140, 300, 111, 51))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_up.setFont(font)
        self.pushButton_up.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(102, 133, 156, 255), stop:1 rgba(117, 255, 201, 255));\n"
"    color: rgb(255, 255, 255);\n"
"    border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_up.setObjectName("pushButton_up")
        self.lineEdit_p = QtWidgets.QLineEdit(self.page_in)
        self.lineEdit_p.setGeometry(QtCore.QRect(20, 210, 221, 51))
        self.lineEdit_p.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(0,0,0,100);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.lineEdit_p.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_p.setObjectName("lineEdit_p")
        self.stackedWidget.addWidget(self.page_in)
        self.page_up = QtWidgets.QWidget()
        self.page_up.setObjectName("page_up")
        self.label_5 = QtWidgets.QLabel(self.page_up)
        self.label_5.setGeometry(QtCore.QRect(70, 40, 131, 71))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_u2 = QtWidgets.QLineEdit(self.page_up)
        self.lineEdit_u2.setGeometry(QtCore.QRect(20, 130, 221, 51))
        self.lineEdit_u2.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(0,0,0,100);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.lineEdit_u2.setObjectName("lineEdit_u2")
        self.pushButton_u = QtWidgets.QPushButton(self.page_up)
        self.pushButton_u.setGeometry(QtCore.QRect(10, 300, 111, 51))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_u.setFont(font)
        self.pushButton_u.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(102, 133, 156, 255), stop:1 rgba(117, 255, 201, 255));\n"
"    color: rgb(255, 255, 255);\n"
"    border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_u.setObjectName("pushButton_u")
        self.pushButton_r = QtWidgets.QPushButton(self.page_up)
        self.pushButton_r.setGeometry(QtCore.QRect(140, 300, 111, 51))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_r.setFont(font)
        self.pushButton_r.setStyleSheet("QPushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(102, 133, 156, 255), stop:1 rgba(117, 255, 201, 255));\n"
"    color: rgb(255, 255, 255);\n"
"    border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_r.setObjectName("pushButton_r")
        self.lineEdit_p2 = QtWidgets.QLineEdit(self.page_up)
        self.lineEdit_p2.setGeometry(QtCore.QRect(20, 210, 221, 51))
        self.lineEdit_p2.setStyleSheet("border:none;\n"
"border-bottom:2px solid rgba(0,0,0,100);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.lineEdit_p2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_p2.setObjectName("lineEdit_p2")
        self.stackedWidget.addWidget(self.page_up)
        self.stackedWidget.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.frame.raise_()
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        self.pushButton_3.clicked.connect(LoginWindow.close) # type: ignore
        self.pushButton_2.clicked.connect(LoginWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)
        LoginWindow.setTabOrder(self.pushButton_2, self.pushButton_3)
        LoginWindow.setTabOrder(self.pushButton_3, self.lineEdit_u)
        LoginWindow.setTabOrder(self.lineEdit_u, self.lineEdit_p)
        LoginWindow.setTabOrder(self.lineEdit_p, self.pushButton_in)
        LoginWindow.setTabOrder(self.pushButton_in, self.pushButton_up)
        LoginWindow.setTabOrder(self.pushButton_up, self.lineEdit_u2)
        LoginWindow.setTabOrder(self.lineEdit_u2, self.lineEdit_p2)
        LoginWindow.setTabOrder(self.lineEdit_p2, self.pushButton_u)
        LoginWindow.setTabOrder(self.pushButton_u, self.pushButton_r)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.label_4.setText(_translate("LoginWindow", "欢迎登录"))
        self.lineEdit_u.setPlaceholderText(_translate("LoginWindow", "账号："))
        self.pushButton_in.setText(_translate("LoginWindow", "登录"))
        self.pushButton_up.setText(_translate("LoginWindow", "注册"))
        self.lineEdit_p.setPlaceholderText(_translate("LoginWindow", "密码："))
        self.label_5.setText(_translate("LoginWindow", "欢迎注册"))
        self.lineEdit_u2.setPlaceholderText(_translate("LoginWindow", "账号："))
        self.pushButton_u.setText(_translate("LoginWindow", "注册"))
        self.pushButton_r.setText(_translate("LoginWindow", "返回"))
        self.lineEdit_p2.setPlaceholderText(_translate("LoginWindow", "密码："))
import res_rc
